### ISSUE TITLE
Update to latest MySql version

### ISSUE THREAD

**Issue by ansarizafar** [yukoff/openshift-cartridge-percona-server#1]
@yukoff  Please updated this cartridge to latest version.

**Comment by yukoff** [comment]
Hi @ansarizafar,

Just updated to latest Percona Server (v5.7.15 at the moment)

**Comment by ansarizafar** [comment]
Hi @yukoff  I am getting this error

![perconaerror](https://cloud.githubusercontent.com/assets/5788284/20169168/d896ee48-a747-11e6-8144-e01e37bc0d41.png)

**Comment by yukoff** [comment]
I see, missed the tarball directory path in install script - should be fine now.
